### ISSUE TITLE
Re-run code to check after re-structuring

### ISSUE THREAD

**Issue by christopherahern** [christopherahern/do-PPCHE#2]

**Comment by christopherahern** [comment]
@bacovcin I've created a new branch that runs and outputs in ~11min. To run it: `git checkout working`. The only difference between the initial commit is the effect of `RemoveDup.py`. Could you remind me what that does and why?

**Comment by bacovcin** [comment]
RemoveDup.py removes tokens that are exact duplicates of each other. This is import for two reasons:

1) Formulaic expressions should probably only be counted once

2) More importantly, there is overlap between texts in the PCEEC and PPCEME, which means that if you don't remove duplicates (or run some other exclusion criterion), you will count the exact same sentence from the same letter multiple times.

**Comment by bacovcin** [comment]
Printing out lines slowed down system; now runs in about 13 minutes on my desktop with lots of other applications running.

**Comment by christopherahern** [comment]
Why python3? What depends on it?

**Comment by bacovcin** [comment]
The main problem is print statements, and I think there may be a way to make those backwards compatible. I use the python3 version, because that is now the default version of python, and will become more so in the future.

**Comment by christopherahern** [comment]
Ahahah, but tell me how you really feel. If nothing depends on it, I would
leave it as `python` rather than `python3`. Other than printing, which I'm
assuming you removed, everything should be the same. Have you pushed a
version that runs and outputs?

-Chris

**Comment by bacovcin** [comment]
I agree. I'll fix that soon and then close this.

**Comment by bacovcin** [comment]
I'm testing it now with python2 to make sure that it is backwards compatible, and then I'll change the make.sh to just python.
