### ISSUE TITLE
Concatenate database files and check for consistency

### ISSUE THREAD

**Issue by christopherahern** [christopherahern/do-PPCHE#3]

**Comment by christopherahern** [comment]
Hey @bacovcin, could you give a quick summary of the data base files in database/?

In particular it seems like Eng_Db.txt has all of the documents at least from looking at `wc -l` of all of them. Is that right? Can we just use that?

**Comment by bacovcin** [comment]
Redid database using token ids instead of letter identifiers for multitext files (new file in English_database.txt).
