### ISSUE TITLE
Replace fill-in-externals.py with bash join

### ISSUE THREAD

**Issue by christopherahern** [christopherahern/do-PPCHE#4]

**Comment by bacovcin** [comment]
Using the new database file, I'm planning to do a join on file id, which should create multiple copies for multitext files. I'll then filter lines where the token id isn't within the range for a given text.

**Comment by bacovcin** [comment]
Bash join does not work with the new system for identifying corpus files with multiple texts. Rewrote python script to be much, much faster.

**Comment by christopherahern** [comment]
How much does much faster mean?

**Comment by bacovcin** [comment]
It now runs in about 3 minutes on the almost million lines of output from the do-support query.

**Comment by christopherahern** [comment]
Aha, that's more like it!

phone
